Repository utsaslab/rustfs, pull requests merged in 2018-09, with the labels that each got.

#6 Add the basic code templates for the SPDK library Rust FFI
  .gitignore
  CMakeLists.txt
  examples/hello_nvme_bdev/CMakeLists.txt
  examples/hello_nvme_bdev/hello_nvme_bdev.c
  examples/hello_nvme_bdev_rust_wrapper/Cargo.toml
  examples/hello_nvme_bdev_rust_wrapper/README.md
  examples/hello_nvme_bdev_rust_wrapper/src/main.rs
  spdk-rs/Cargo.toml
  spdk-rs/README.md
  spdk-rs/libspdk-sys/.cargo/config
  spdk-rs/libspdk-sys/Cargo.toml
  spdk-rs/libspdk-sys/build.rs
  spdk-rs/libspdk-sys/src/lib.rs
  spdk-rs/libspdk-sys/src/wrapper.h
  spdk-rs/src/bdev.rs
  spdk-rs/src/lib.rs
Labels: revisit in future

#7 Merge 1.0 dev to master
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  CMakeLists.txt
  CMakeModules/Macros.cmake
  README.md
  examples/README.md
  examples/hello_nvme_bdev/CMakeLists.txt
  examples/hello_nvme_bdev/README.md
  examples/hello_nvme_bdev/bdev.conf
  examples/hello_nvme_bdev/hello_nvme_bdev.c
  examples/hello_nvme_bdev_rust/.cargo/config
  examples/hello_nvme_bdev_rust/Cargo.toml
  examples/hello_nvme_bdev_rust/README.md
  examples/hello_nvme_bdev_rust/build.rs
  examples/hello_nvme_bdev_rust/src/main.rs
  examples/hello_nvme_bdev_rust/src/wrapper.h
  examples/hello_nvme_bdev_rust_wrapper/Cargo.toml
  examples/hello_nvme_bdev_rust_wrapper/README.md
  examples/hello_nvme_bdev_rust_wrapper/src/main.rs
  spdk-rs/Cargo.toml
  spdk-rs/README.md
  spdk-rs/libspdk-sys/.cargo/config
  spdk-rs/libspdk-sys/Cargo.toml
  spdk-rs/libspdk-sys/build.rs
  spdk-rs/libspdk-sys/src/lib.rs
  spdk-rs/libspdk-sys/src/wrapper.h
  spdk-rs/src/bdev.rs
  spdk-rs/src/lib.rs
Labels: Logistics

#14 Using RUSTFLAGS to do linking instead of .cargo/config
  examples/hello_nvme_bdev_rust/.cargo/config
  examples/hello_nvme_bdev_rust/build.rs
Labels: enhancement
